server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

spring:
  application:
    name: confession-wall

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:confession_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:8080,http://localhost,http://127.0.0.1:5173,http://127.0.0.1:8080,http://127.0.0.1}
